# 9/23 機械学習入門
## Cancer_logistic.py


In [1]:
# ロジスティック回帰
import sys
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression

# データのロード
cancer = datasets.load_breast_cancer()

# 特徴量（30次元）
feature_names=cancer.feature_names
data = cancer.data

# 目的変数( malignant, benign )
name = cancer.target_names
label = cancer.target #分類問題では正解値として正解ラベルを学習時に与える,二値分類問題では，正例(1)もしくは負例(0)

# ホールドアウト法（学習データ，テストデータ）
train_data, test_data, train_label, test_label = train_test_split(data, label, test_size=0.5, random_state=None)

# ロジスティック回帰 
# (ソルバー：記憶制限付き準ニュートン法 L-BFGS)
# (ペナルティ項：2ノルム)
model = LogisticRegression(C=1.0,penalty='l2',solver='lbfgs',max_iter=100)

# 学習
model.fit(train_data, train_label)

# 予測
predict = model.predict(test_data)

# 係数と切片
print( '\n 係数ベクトル : ' , model.coef_ )
print( ' 切片 : ' , model.intercept_)

# 予測値，教師ラベル
print( '\n [ 予測値  :  教師ラベル ]' )
predict_proba = model.predict_proba(test_data)
for i in range(len(test_label)):
    print( predict_proba[i] , ':' , test_label[i] ) #predict_proba[i] = [p(0),p(1)][i]
    

# 予測結果の表示
print( "\n [ 予測結果 ]" )
print( ' accuracy  : ' , accuracy_score(test_label, predict) )
print( ' precision : ' , precision_score(test_label, predict) )
print( ' recall    : ' , recall_score(test_label, predict) )
print( ' f1-score  : ' , f1_score(test_label, predict) )

print( "\n [ 予測結果 ]" )
print( classification_report(test_label, predict) )

print( "\n [ 混同行列 ]" )
print( confusion_matrix(test_label, predict) )





 係数ベクトル :  [[ 0.82681946  0.35173963 -0.01914773  0.00649207 -0.02922726 -0.12739429
  -0.1884239  -0.0903814  -0.04906286 -0.00526464  0.04573603  0.20991506
   0.16554865 -0.11526574 -0.00561732 -0.02680734 -0.04446087 -0.01463333
  -0.00478777 -0.00240801  0.88923911 -0.39089774  0.04090957 -0.03223482
  -0.05775775 -0.32373208 -0.47230005 -0.15816935 -0.08923601 -0.0267871 ]]
 切片 :  [0.15434619]

 [ 予測値  :  教師ラベル ]
[0.00494191 0.99505809] : 1
[9.99369756e-01 6.30243735e-04] : 0
[0.02608425 0.97391575] : 1
[0.82289334 0.17710666] : 0
[9.99880641e-01 1.19358741e-04] : 0
[9.99999995e-01 5.38927092e-09] : 0
[1.00000000e+00 1.73449413e-15] : 0
[0.01095828 0.98904172] : 1
[0.0048003 0.9951997] : 1
[6.81098490e-04 9.99318902e-01] : 1
[0.04124127 0.95875873] : 1
[9.99978340e-01 2.16601601e-05] : 0
[9.99663496e-01 3.36503558e-04] : 0
[0.67729601 0.32270399] : 0
[0.17275854 0.82724146] : 1
[0.41888106 0.58111894] : 1
[0.00752642 0.99247358] : 1
[0.01854892 0.98145108] : 1
[0.04097022 0.9590

In [12]:
# データのロード
cancer = datasets.load_breast_cancer()

# 特徴量（30次元）
feature_names=cancer.feature_names
data = cancer.data

# 目的変数( malignant, benign )
name = cancer.target_names
label = cancer.target
#print(cancer.feature_names)
print(cancer.data)
len(cancer.data)
#print(name)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


569

## logistic_CV.py

In [11]:
# ロジスティック回帰（交叉検証）
import sys
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

# データのロード
cancer = datasets.load_breast_cancer()

# 特徴量（30次元）
feature_names=cancer.feature_names
data = cancer.data

# 目的変数( malignant, benign )
name = cancer.target_names
label = cancer.target

# ロジスティック回帰
model = LogisticRegression(C=1.0,penalty='l2',solver='lbfgs',max_iter=100)

# 交叉検証
score = { "accuracy": "accuracy",
            "precision": "precision_macro",
            "recall": "recall_macro",
            "f":"f1_macro"
            }

result = cross_validate(model, data, label, cv=5, scoring=score,)

# 結果の表示
for i , j in result.items():
    print( " {0:15s} : {1}".format( i , j ) )

 fit_time        : [0.07477999 0.0356791  0.03619599 0.03664112 0.04191089]
 score_time      : [0.00328898 0.00317788 0.00240493 0.00232387 0.00252509]
 test_accuracy   : [0.92982456 0.92982456 0.96491228 0.93859649 0.95575221]
 test_precision  : [0.94103194 0.92916806 0.96722973 0.93601737 0.95083056]
 test_recall     : [0.9115624  0.9207337  0.95734127 0.93154762 0.95506372]
 test_f          : [0.92297297 0.92460317 0.96191113 0.93369339 0.95285774]


## logistic_GS.py

In [14]:
# ロジスティック回帰
import sys
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split, GridSearchCV #グリッドサーチのためのライブラリ
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression

# データのロード
cancer = datasets.load_breast_cancer()

# 特徴量（30次元）
feature_names=cancer.feature_names
data = cancer.data

# 目的変数( malignant, benign )
name = cancer.target_names
label = cancer.target

# ホールドアウト法（学習データ，テストデータ）
train_data, test_data, train_label, test_label = train_test_split(data, label, test_size=0.5, random_state=None)

# グリッドサーチ
parameters = {'C': [ 0.2, 1.0 ],
              'penalty' : [ 'l1' , 'l2' , 'none' ],
              'solver' : [ 'newton-cg', 'lbfgs' ],
              'max_iter' : [ 100 , 200 ]
              }

# ロジスティック回帰によるグリッドサーチ           
model = GridSearchCV(LogisticRegression(), parameters, cv=5)

# 学習
model.fit(train_data, train_label)

# 最良モデル( 変数 model は最良なモデルが求まっている ）
best_model = model.best_estimator_

print( "\n [ 最良なパラメータ ]" )
print( model.best_params_ )

# 予測
predict = best_model.predict(test_data)

# 係数と切片
print( '\n 係数ベクトル : ' , best_model.coef_ )
print( ' 切片 : ' , best_model.intercept_)

# 予測値，教師ラベル
print( '\n [ 予測値  :  教師ラベル ]' )
predict_proba = best_model.predict_proba(test_data)
for i in range(len(test_label)):
    print( predict_proba[i] , ':' , test_label[i] )
    
# 予測結果の表示
print( "\n [ 予測結果 ]" )
print( ' accuracy  : ' , accuracy_score(test_label, predict) )
print( ' precision : ' , precision_score(test_label, predict) )
print( ' recall    : ' , recall_score(test_label, predict) )
print( ' f1-score  : ' , f1_score(test_label, predict) )

print( "\n [ 予測結果 ]" )
print( classification_report(test_label, predict) )

print( "\n [ 混同行列 ]" )
print( confusion_matrix(test_label, predict) )

# 交叉検証の結果
#print( "\n [ 交叉検証の全結果 ]" )
#for i ,  j in model.cv_results_.items():
#    print( i , " : " , j )


 [ 最良なパラメータ ]
{'C': 0.2, 'max_iter': 100, 'penalty': 'none', 'solver': 'newton-cg'}

 係数ベクトル :  [[ 5.52904987e+00 -1.59149498e+00  8.03708547e-01 -7.67465823e-02
  -1.64261464e+01  3.66204844e+01 -2.22085957e+01 -3.43412539e+01
   8.60696490e+00  7.69871710e+00 -1.58642740e+01 -1.33425114e+00
  -9.54645170e-01 -9.34909375e-02 -1.42542310e+00  5.92780944e+01
   4.06252598e+01 -1.03357356e+01  1.70885973e+01  9.55782994e+00
  -4.11254997e+00  6.67883448e-01 -1.10208873e-01  5.96284645e-04
  -3.81623953e+01  1.56962300e+01 -1.94389982e+01 -9.17632353e+01
  -3.17481233e+01  7.29211198e+00]]
 切片 :  [23.10940642]

 [ 予測値  :  教師ラベル ]
[3.37175429e-04 9.99662825e-01] : 1
[1.00000000e+00 1.00582191e-70] : 0
[1.97221580e-04 9.99802778e-01] : 1
[3.29373981e-08 9.99999967e-01] : 1
[9.99999827e-01 1.72853863e-07] : 0
[1.73804829e-05 9.99982620e-01] : 1
[6.22962992e-09 9.99999994e-01] : 1
[1.00000000e+00 4.45889628e-15] : 0
[1.89004520e-04 9.99810995e-01] : 1
[1.42514297e-06 9.99998575e-01] : 1
[2.7